package org.example;

import java.util.ArrayList;
import java.util.List;

/**
 * Problem 2 - Even Fibonacci Numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 * even-valued terms.
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        long result = solution(4000000);
        System.out.println(result);
    }

    public static long solution(int limit) {
        // every third value in the sequence is even....
        long sum = 0;
        int firstVal = 1;
        int secondVal = 1;
        int thirdVal = firstVal + secondVal;
        while (thirdVal < limit) {
            firstVal = secondVal;
            secondVal = thirdVal;
            thirdVal = firstVal + secondVal;

            if (thirdVal % 2 == 0) {
                sum += thirdVal;
            }
        }

        return sum;
    }
}
